# Each page blueprint must have a title, the title may be different from the file name
# This default blueprint is used to display a page in the Panel whenever a custom page blueprint is missing.
title: Simple Page

# Each page can have an icon that is shown in page listings when no preview image is available.
icon: 📝

# Custom descriptions of page statuses depending on use case
# More about page statuses: https://getkirby.com/docs/reference/panel/blueprints/page#statuses
status:
  draft: true
  unlisted:
    label: Hidden Page
    text: The page is not listed in the main menu
  listed:
    label: Menu Page
    text: The page is listed in the main menu

# All fields are defined once at the root level of the blueprint
# and referenced by name in the columns below
fields:
  text:
    type: textarea
    size: huge
  # Pagelist field: https://getkirby.com/docs/reference/panel/fields/pagelist
  pages:
    type: pagelist
    template: default
  # Filelist field: https://getkirby.com/docs/reference/panel/fields/filelist
  files:
    type: filelist

# Content area with 2 columns: a textarea in the main column,
# subpages and files in the sidebar
# Columns: https://getkirby.com/docs/guide/blueprints/layout#defining-columns
columns:
  main:
    width: 2/3
    fields:
      - text
  sidebar:
    width: 1/3
    fields:
      - pages
      - files
