# The `site.yml` blueprint defines the look of the start page (Dashboard) of the Panel.

# The site blueprint usually provides easy access to all main pages of the site.
# In this example blueprint, we also show subpages of the `photography` and `notes` pages.
# More about the site blueprint: https://getkirby.com/docs/reference/panel/blueprints/site

fields:
  # The `albums` field lists the subpages of the `photography` page in card layout
  # It reuses the pagelist field defined in `/site/blueprints/fields/albums.yml`
  albums: fields/albums

  # The `notes` field reuses the pagelist field defined in `/site/blueprints/fields/notes.yml`
  notes:
    extends: fields/notes
    status: listed

  # The `pages` pagelist field shows other main pages of the site
  # Using the `templates` option, we limit which types of pages are shown
  # Using the `create` option, we limit the type of page that can be created when a new page is created
  # Note that the `sandbox` page and the `error` page that also exist in the content folder but use different blueprints thus do not show up in the list
  # Since the error page's blueprint is set to `read: false`, it wouldn't show up here even if you added the error blueprint to the templates list
  pages:
    type: pagelist
    create: default
    templates:
      - about
      - home
      - default

# The layout of this form has two columns:
# the first one for the albums, the second one for the notes and pages
columns:
  - width: 1/2
    fields:
      - albums

  - width: 1/2
    fields:
      - notes
      - pages
